a=int(input("Enter the value of A : "))
b=int(input("Enter the value of B : "))
print("Result of comparison")
print("a==b ->",a==b)
print("a!=b ->",a!=b)
print("a>b ->",a>b)
print("a<b ->",a<b)
print("a>=b ->",a>=b)
print("a<=b ->",a<=b)